package com.corporation.pharmacy.dao;

import com.corporation.pharmacy.dao.exception.DaoException;
import com.corporation.pharmacy.entity.User;

/**
 * The Interface UserDAO
 * 
 * defines methods for working with user.
 */
public interface UserDAO {

    // ADD operations

    /**
     * Adds a new user to the data base. Returns the id of this user generated by
     * the data base.
     *
     * @param user
     *            the user
     * @return the id of added user
     * @throws DaoException
     *             the exception during getting connection with data base or during
     *             working with data base.
     */
    Integer addUser(User user) throws DaoException;

    // GET operations

    /**
     * Checks if the email or login exists already in the data base. Returns
     * <code>true<\code> if exists, <code>false<\code> if not.
     *
     * @param user
     *            the user object consisting email and login as fields
     * @return true if email or login exists in data base, false if neither email,
     *         nor login exists
     * @throws DaoException
     *             the exception during getting connection with data base or during
     *             working with data base.
     */
    boolean isEmailOrLoginExists(User user) throws DaoException;

    /**
     * Gets the user by login or email and password. Returns null if the user with
     * such parameters doesn't exist.
     *
     * @param loginOrEmail
     *            <code>String</code> representing a login or email
     * @param password
     *            the password
     * @return the user object if user with such parameters exists, null if not
     *         exists
     * @throws DaoException
     *             the exception during getting connection with data base or during
     *             working with data base.
     */
    User getUser(String loginOrEmail, String password) throws DaoException;

    /**
     * Gets the user name by its id.
     *
     * @param idUser
     *            the id user
     * @return the user name
     * @throws DaoException
     *             the exception during getting connection with data base or during
     *             working with data base.
     */
    String getUserName(Integer idUser) throws DaoException;

    // UPDATE operations

    /**
     * Sets to existing user additional info. The user should have been added
     * already before using this method.
     *
     * @param user
     *            with filling fields
     * @throws DaoException
     *             the exception during getting connection with data base or during
     *             working with data base.
     */
    void setUserFullInfo(User user) throws DaoException;

}
